name: Auto-label Issues

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add labels
      run: |
        # Extract the issue title
        ISSUE_TITLE=$(jq -r .issue.title "$GITHUB_EVENT_PATH")

        # Add labels based on the issue title
        if [[ $ISSUE_TITLE == *bug* ]]; then
          echo "Adding label: bug"
          gh issues add-label "$GITHUB_ISSUE_NUMBER" bug
        elif [[ $ISSUE_TITLE == *feature* ]]; then
          echo "Adding label: feature"
          gh issues add-label "$GITHUB_ISSUE_NUMBER" feature
        else
          echo "No matching label found."
        fi

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
