name: Docker Container Action 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Docker container action
      uses: docker://alpine:3.14
      with:
        args: echo "Hello from Docker container action"
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: echo "Running tests"
